import { useMemo, useState } from "react";
import { usePneus, usePneuManutencao } from "@/lib/store";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, Gauge, Hammer, Recycle, Ruler, SearchCheck } from "lucide-react";
import { toast } from "sonner";

const today=()=>new Date().toISOString().slice(0,10);
const readImages=async(files:FileList|null)=>{if(!files)return[] as string[];return Promise.all(Array.from(files).slice(0,10).map(file=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);})));};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-1.5"><Label>{label}</Label>{children}</div>;
export function PneuManutencao(){
 const {items}=usePneus(); const [pneuId,setPneuId]=useState(items[0]?.id??""); const {data,addSulco,addCalibragem,addRecapagem,addConserto,addInspecao}=usePneuManutencao(pneuId); const pneu=items.find(p=>p.id===pneuId);
 const [sulco,setSulco]=useState({data:today(),quilometragem:"",sulcoInterno:"",sulcoCentral:"",sulcoExterno:"",responsavel:"",observacoes:""});
 const [cal,setCal]=useState({data:today(),pressaoRecomendada:"",pressaoEncontrada:"",pressaoAjustada:"",responsavel:"",observacoes:""});
 const [rec,setRec]=useState({empresaRecapadora:"",dataEnvio:today(),dataRetorno:"",valor:"",garantiaMeses:"0",tipoRecapagem:"",numeroRecapagem:String((pneu?.recapagensRealizadas??0)+1),observacoes:""});
 const [con,setCon]=useState({tipo:"FURO",data:today(),valor:"0",responsavel:"",observacoes:"",fotosAntes:[] as string[],fotosDepois:[] as string[]});
 const [ins,setIns]=useState({data:today(),responsavel:"",pressaoOk:true,sulcoOk:true,cortes:false,bolhas:false,trincas:false,desgasteIrregular:false,lonaAparente:false,observacoes:"",fotos:[] as string[]});
 const latestSulco=data?.medicoesSulco[0]; const latestCal=data?.calibragens[0]; const latestIns=data?.inspecoes[0];
 const alerts=useMemo(()=>{const a:string[]=[]; if(latestSulco&&latestSulco.mediaSulco<=2)a.push("Sulco abaixo do limite de segurança"); if(latestCal&&Math.abs(latestCal.pressaoEncontrada-latestCal.pressaoRecomendada)/latestCal.pressaoRecomendada>0.1)a.push("Pressão fora do padrão"); if(pneu&&pneu.recapagensRealizadas>=pneu.maxRecapagens)a.push("Máximo de recapagens atingido"); if(!latestIns||Date.now()-new Date(latestIns.data+"T12:00:00").getTime()>30*86400000)a.push("Pneu sem inspeção há mais de 30 dias"); return a;},[latestSulco,latestCal,latestIns,pneu]);
 const submit=async(fn:()=>Promise<unknown>,msg:string)=>{try{await fn();toast.success(msg);}catch(e:any){toast.error(e?.response?.data?.message||"Não foi possível salvar.");}};
 return <div className="space-y-4">
  <Card><CardContent className="p-4"><Field label="Pneu"><Select value={pneuId} onValueChange={setPneuId}><SelectTrigger><SelectValue placeholder="Selecione um pneu"/></SelectTrigger><SelectContent>{items.map(p=><SelectItem key={p.id} value={p.id}>{p.numeroFogo} — {p.marca} {p.modelo}</SelectItem>)}</SelectContent></Select></Field></CardContent></Card>
  {pneu&&<div className="grid gap-3 md:grid-cols-4"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Sulco atual</p><p className="text-2xl font-bold">{latestSulco?`${latestSulco.mediaSulco.toFixed(2)} mm`:pneu.sulcoAtual!=null?`${pneu.sulcoAtual} mm`:"—"}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Vida útil restante</p><p className="text-2xl font-bold">{latestSulco?`${latestSulco.vidaUtilRestante.toFixed(1)}%`:"—"}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Recapagens</p><p className="text-2xl font-bold">{pneu.recapagensRealizadas}/{pneu.maxRecapagens}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Alertas ativos</p><p className="text-2xl font-bold">{alerts.length}</p></CardContent></Card></div>}
  {alerts.length>0&&<Card className="border-destructive/50"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle className="h-4 w-4 text-destructive"/>Alertas</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{alerts.map(a=><Badge key={a} variant="destructive">{a}</Badge>)}</CardContent></Card>}
  <Tabs defaultValue="sulco"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="sulco">Sulco</TabsTrigger><TabsTrigger value="calibragem">Calibragem</TabsTrigger><TabsTrigger value="recapagem">Recapagem</TabsTrigger><TabsTrigger value="consertos">Consertos</TabsTrigger><TabsTrigger value="inspecoes">Inspeções</TabsTrigger></TabsList>
   <TabsContent value="sulco" className="mt-4 grid gap-4 lg:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Ruler className="h-4 w-4"/>Nova medição</CardTitle></CardHeader><CardContent className="grid gap-3"><Field label="Data"><Input type="date" value={sulco.data} onChange={e=>setSulco({...sulco,data:e.target.value})}/></Field><div className="grid grid-cols-3 gap-2"><Field label="Interno"><Input type="number" step="0.1" value={sulco.sulcoInterno} onChange={e=>setSulco({...sulco,sulcoInterno:e.target.value})}/></Field><Field label="Central"><Input type="number" step="0.1" value={sulco.sulcoCentral} onChange={e=>setSulco({...sulco,sulcoCentral:e.target.value})}/></Field><Field label="Externo"><Input type="number" step="0.1" value={sulco.sulcoExterno} onChange={e=>setSulco({...sulco,sulcoExterno:e.target.value})}/></Field></div><Field label="Quilometragem"><Input type="number" value={sulco.quilometragem} onChange={e=>setSulco({...sulco,quilometragem:e.target.value})}/></Field><Field label="Responsável"><Input value={sulco.responsavel} onChange={e=>setSulco({...sulco,responsavel:e.target.value})}/></Field><Button onClick={()=>submit(()=>addSulco({...sulco,quilometragem:sulco.quilometragem?Number(sulco.quilometragem):null,sulcoInterno:Number(sulco.sulcoInterno),sulcoCentral:Number(sulco.sulcoCentral),sulcoExterno:Number(sulco.sulcoExterno)}),"Medição registrada")}>Salvar medição</Button></CardContent></Card><div className="space-y-4"><WearChart values={[...(data?.medicoesSulco??[])].reverse().map(x=>({label:new Date(x.data+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),value:x.mediaSulco}))}/><HistoryList title="Evolução do desgaste" rows={(data?.medicoesSulco??[]).map(x=>({date:x.data,title:`${x.mediaSulco.toFixed(2)} mm — ${x.percentualDesgaste.toFixed(1)}% de desgaste`,detail:`Vida restante: ${x.vidaUtilRestante.toFixed(1)}% • ${x.responsavel}`}))}/></div></TabsContent>
   <TabsContent value="calibragem" className="mt-4 grid gap-4 lg:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Gauge className="h-4 w-4"/>Nova calibragem</CardTitle></CardHeader><CardContent className="grid gap-3"><Field label="Data"><Input type="date" value={cal.data} onChange={e=>setCal({...cal,data:e.target.value})}/></Field><Field label="Pressão recomendada"><Input type="number" value={cal.pressaoRecomendada} onChange={e=>setCal({...cal,pressaoRecomendada:e.target.value})}/></Field><Field label="Pressão encontrada"><Input type="number" value={cal.pressaoEncontrada} onChange={e=>setCal({...cal,pressaoEncontrada:e.target.value})}/></Field><Field label="Pressão ajustada"><Input type="number" value={cal.pressaoAjustada} onChange={e=>setCal({...cal,pressaoAjustada:e.target.value})}/></Field><Field label="Responsável"><Input value={cal.responsavel} onChange={e=>setCal({...cal,responsavel:e.target.value})}/></Field><Button onClick={()=>submit(()=>addCalibragem({...cal,pressaoRecomendada:Number(cal.pressaoRecomendada),pressaoEncontrada:Number(cal.pressaoEncontrada),pressaoAjustada:Number(cal.pressaoAjustada)}),"Calibragem registrada")}>Salvar calibragem</Button></CardContent></Card><HistoryList title="Histórico de calibragem" rows={(data?.calibragens??[]).map(x=>({date:x.data,title:`Encontrada ${x.pressaoEncontrada} • Ajustada ${x.pressaoAjustada}`,detail:`Recomendada ${x.pressaoRecomendada} • ${x.responsavel}`}))}/></TabsContent>
   <TabsContent value="recapagem" className="mt-4 grid gap-4 lg:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Recycle className="h-4 w-4"/>Nova recapagem</CardTitle></CardHeader><CardContent className="grid gap-3"><Field label="Empresa recapadora"><Input value={rec.empresaRecapadora} onChange={e=>setRec({...rec,empresaRecapadora:e.target.value})}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Envio"><Input type="date" value={rec.dataEnvio} onChange={e=>setRec({...rec,dataEnvio:e.target.value})}/></Field><Field label="Retorno"><Input type="date" value={rec.dataRetorno} onChange={e=>setRec({...rec,dataRetorno:e.target.value})}/></Field></div><Field label="Tipo"><Input value={rec.tipoRecapagem} onChange={e=>setRec({...rec,tipoRecapagem:e.target.value})}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Número"><Input type="number" value={rec.numeroRecapagem} onChange={e=>setRec({...rec,numeroRecapagem:e.target.value})}/></Field><Field label="Valor"><Input type="number" step="0.01" value={rec.valor} onChange={e=>setRec({...rec,valor:e.target.value})}/></Field></div><Field label="Garantia (meses)"><Input type="number" value={rec.garantiaMeses} onChange={e=>setRec({...rec,garantiaMeses:e.target.value})}/></Field><Button onClick={()=>submit(()=>addRecapagem({...rec,valor:Number(rec.valor),garantiaMeses:Number(rec.garantiaMeses),numeroRecapagem:Number(rec.numeroRecapagem),dataRetorno:rec.dataRetorno||null}),"Recapagem registrada")}>Salvar recapagem</Button></CardContent></Card><HistoryList title="Histórico de recapagens" rows={(data?.recapagens??[]).map(x=>({date:x.dataEnvio,title:`${x.numeroRecapagem}ª recapagem — ${x.empresaRecapadora}`,detail:`${x.tipoRecapagem} • ${money(x.valor)}${x.dataRetorno?` • retorno ${new Date(x.dataRetorno+"T12:00:00").toLocaleDateString("pt-BR")}`:""}`}))}/></TabsContent>
   <TabsContent value="consertos" className="mt-4 grid gap-4 lg:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Hammer className="h-4 w-4"/>Novo conserto</CardTitle></CardHeader><CardContent className="grid gap-3"><Field label="Tipo"><Select value={con.tipo} onValueChange={v=>setCon({...con,tipo:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[["FURO","Furo"],["REMENDO","Remendo"],["VULCANIZACAO","Vulcanização"],["CORTE_LATERAL","Corte lateral"],["OUTRO","Outro"]].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></Field><Field label="Data"><Input type="date" value={con.data} onChange={e=>setCon({...con,data:e.target.value})}/></Field><Field label="Valor"><Input type="number" step="0.01" value={con.valor} onChange={e=>setCon({...con,valor:e.target.value})}/></Field><Field label="Responsável"><Input value={con.responsavel} onChange={e=>setCon({...con,responsavel:e.target.value})}/></Field><Field label="Observações"><Textarea value={con.observacoes} onChange={e=>setCon({...con,observacoes:e.target.value})}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Fotos antes"><Input type="file" accept="image/*" multiple onChange={e=>void readImages(e.target.files).then(fotosAntes=>setCon({...con,fotosAntes}))}/></Field><Field label="Fotos depois"><Input type="file" accept="image/*" multiple onChange={e=>void readImages(e.target.files).then(fotosDepois=>setCon({...con,fotosDepois}))}/></Field></div><Button onClick={()=>submit(()=>addConserto({...con,valor:Number(con.valor)}),"Conserto registrado")}>Salvar conserto</Button></CardContent></Card><HistoryList title="Histórico de consertos" rows={(data?.consertos??[]).map(x=>({date:x.data,title:x.tipo.replaceAll("_"," "),detail:`${money(x.valor)} • ${x.responsavel}`}))}/></TabsContent>
   <TabsContent value="inspecoes" className="mt-4 grid gap-4 lg:grid-cols-[420px_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><SearchCheck className="h-4 w-4"/>Nova inspeção</CardTitle></CardHeader><CardContent className="grid gap-3"><Field label="Data"><Input type="date" value={ins.data} onChange={e=>setIns({...ins,data:e.target.value})}/></Field><Field label="Responsável"><Input value={ins.responsavel} onChange={e=>setIns({...ins,responsavel:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3">{[["pressaoOk","Pressão adequada"],["sulcoOk","Sulco adequado"],["cortes","Cortes"],["bolhas","Bolhas"],["trincas","Trincas"],["desgasteIrregular","Desgaste irregular"],["lonaAparente","Lona aparente"]].map(([k,l])=><label key={k} className="flex items-center gap-2 text-sm"><Checkbox checked={(ins as any)[k]} onCheckedChange={v=>setIns({...ins,[k]:Boolean(v)})}/>{l}</label>)}</div><Field label="Observações"><Textarea value={ins.observacoes} onChange={e=>setIns({...ins,observacoes:e.target.value})}/></Field><Field label="Fotos"><Input type="file" accept="image/*" multiple onChange={e=>void readImages(e.target.files).then(fotos=>setIns({...ins,fotos}))}/></Field><Button onClick={()=>submit(()=>addInspecao(ins),"Inspeção registrada")}>Salvar inspeção</Button></CardContent></Card><HistoryList title="Histórico de inspeções" rows={(data?.inspecoes??[]).map(x=>{const probs=[x.cortes&&"cortes",x.bolhas&&"bolhas",x.trincas&&"trincas",x.desgasteIrregular&&"desgaste irregular",x.lonaAparente&&"lona aparente"].filter(Boolean);return{date:x.data,title:probs.length?`Alertas: ${probs.join(", ")}`:"Sem anomalias",detail:x.responsavel}})}/></TabsContent>
  </Tabs>
 </div>;
}
function HistoryList({title,rows}:{title:string;rows:Array<{date:string;title:string;detail:string}>}){return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent>{rows.length===0?<p className="text-sm text-muted-foreground">Nenhum registro.</p>:<div className="space-y-3">{rows.map((r,i)=><div key={i} className="border-b pb-3 last:border-0"><p className="text-sm font-medium">{r.title}</p><p className="text-xs text-muted-foreground">{new Date(r.date+"T12:00:00").toLocaleDateString("pt-BR")} • {r.detail}</p></div>)}</div>}</CardContent></Card>}

function WearChart({values}:{values:Array<{label:string;value:number}>}){const max=Math.max(1,...values.map(v=>v.value));return <Card><CardHeader><CardTitle className="text-base">Gráfico de evolução do sulco</CardTitle></CardHeader><CardContent>{values.length<2?<p className="text-sm text-muted-foreground">Registre ao menos duas medições para visualizar a evolução.</p>:<div className="flex h-44 items-end gap-2">{values.slice(-12).map((v,i)=><div key={i} className="flex min-w-0 flex-1 flex-col items-center gap-1"><span className="text-[10px] text-muted-foreground">{v.value.toFixed(1)}</span><div className="w-full rounded-t bg-primary" style={{height:`${Math.max(8,(v.value/max)*120)}px`}}/><span className="text-[9px] text-muted-foreground">{v.label}</span></div>)}</div>}</CardContent></Card>}
