ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "telefone" TEXT,
ADD COLUMN IF NOT EXISTS "cpf" TEXT,
ADD COLUMN IF NOT EXISTS "fotoPerfil" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "users_cpf_key"
ON "users" ("cpf");