ALTER TABLE "ciots"
ADD COLUMN "outrosValores" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "descontos" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "valorLiquido" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "formaPagamento" TEXT NOT NULL DEFAULT '',
ADD COLUMN "favorecidoPix" TEXT NOT NULL DEFAULT '',
ADD COLUMN "payloadAntt" JSONB,
ADD COLUMN "preparadoEm" TIMESTAMP(3);
