-- Níveis de acesso do módulo de pneus.
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GERENTE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BORRACHARIA';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANUTENCAO';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VISUALIZACAO';
